name: helloworld
on:
  push:
    branches:
      - main  
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with: 
        python-version: "3.10"
        
    - name: Run Hello World
      run: |
          python ap.py
